// Code generated by mockery v2.14.1. DO NOT EDIT.

package main

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockMetaEventbusInterface is an autogenerated mock type for the MetaEventbusInterface type
type MockMetaEventbusInterface struct {
	mock.Mock
}

// sendCurrentYearEvent provides a mock function with given fields: year
func (_m *MockMetaEventbusInterface) sendCurrentYearEvent(year int) error {
	ret := _m.Called(year)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(year)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// sendSecondaryDbLoadedEvent provides a mock function with given fields: currentDatabaseStateDatetime, previousDatabaseStateDatetime, year
func (_m *MockMetaEventbusInterface) sendSecondaryDbLoadedEvent(currentDatabaseStateDatetime time.Time, previousDatabaseStateDatetime time.Time, year int) error {
	ret := _m.Called(currentDatabaseStateDatetime, previousDatabaseStateDatetime, year)

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time, int) error); ok {
		r0 = rf(currentDatabaseStateDatetime, previousDatabaseStateDatetime, year)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockMetaEventbusInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMetaEventbusInterface creates a new instance of MockMetaEventbusInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMetaEventbusInterface(t mockConstructorTestingTNewMockMetaEventbusInterface) *MockMetaEventbusInterface {
	mock := &MockMetaEventbusInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
